# Visualización Interactiva con Plotly

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/dpalacioj/DataAI-Fundamentos-Aplicaciones/blob/main/Analitica/ciencia_datos_con_python/notebooks_teoria/05_1_plotly.ipynb)

## PLOTLY: Libreria de Visualizacion Interactiva

Plotly es una libreria de graficos interactivos de código abierto que admite más de 40 tipos de gráficos únicos que cubren una amplia gama de casos de uso estadísticos, financieros, geográficos, científicos y tridimensionales.

Ademas de ser interactivo y obtener los valores en cada punto de la gráfica, **se pueden mezclar datos numéricos y categóricos.**

## Importar Plotly express

Plotly express es un modulo para usar de forma rapida y concisa de usar la visualización interactiva de plotly

**Nota: Los datos siempre deben estar en un dataframe**

In [1]:
import plotly.express as px

## Datos integrados en Plotly

Plotly viene con algunos data sets clasicos integrados para hacer pruebas:

* carshare
* election
* gapminder
* iris
* tips
* wind

También se pueden encontar otros datasets clasicos de demostracion en formato `.csv` en: https://github.com/mwaskom/seaborn-data

In [2]:
tips = px.data.tips() # Importar el dataset tips
type(tips)

pandas.core.frame.DataFrame

In [3]:
print(px.data.tips.__doc__)

    Each row represents a restaurant bill.

    https://vincentarelbundock.github.io/Rdatasets/doc/reshape2/tips.html

    Returns:
        A `pandas.DataFrame` with 244 rows and the following columns:
        `['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']`.

In [4]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
tips.dtypes

total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

In [6]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

## Tipos de gráficos con Plotly

### Líneas

In [7]:
px.line(tips,y='total_bill',title='Valor Total de la Cuenta')

### Barras

In [8]:
px.bar(tips, x="sex", y="total_bill")

In [9]:
px.bar(tips, x="sex", y="total_bill", color='sex')

### Histograma

In [10]:
px.histogram(tips,'total_bill',title='Histograma Valor Total de la Cuenta')

In [11]:
px.histogram(tips,'sex',title='Histograma de Generos')

In [12]:
px.histogram(tips,'day',
             category_orders= {'day': ["Thur","Fri","Sat", "Sun"]},
             title='Histograma de Dias')

### Box Plot

In [13]:
px.box(tips,y='total_bill', title='Boxplot Valor Total de la Cuenta')

In [14]:
px.box(tips,x = 'day',y='total_bill', color='day',
       title='Boxplots por dia del Valor Total de la Cuenta')

In [16]:
px.box(tips,x = 'day',y='total_bill', title= 'Boxplot por dia con dias en orden',
       category_orders= {'day': ["Thur","Fri","Sat", "Sun"]})

In [17]:
px.box(tips,x = 'day',y='total_bill', color='smoker', category_orders= {'day': ["Thur","Fri","Sat", "Sun"]})

In [18]:
px.box(tips,x = 'day',y='total_bill', color='smoker',
       boxmode='overlay',
       title = 'Boxplots de cuenta total por dia, fumador o no , sobrepuestos ',
       category_orders= {'day': ["Thur","Fri","Sat", "Sun"]})

### Scatter Plot

El dataset gapminder es un conjunto de datos muy utilizado en ciencia de datos, estadística y visualización para ilustrar el desarrollo socioeconómico de los países a lo largo del tiempo. Se hizo famoso gracias a las presentaciones del doctor Hans Rosling, fundador de la fundación Gapminder.

**Dataset Gapminder**

| Columna    | Descripción                                                                 |
|------------|------------------------------------------------------------------------------|
| `country`  | Nombre del país.                                                             |
| `continent`| Continente al que pertenece el país.                                         |
| `year`     | Año de observación (normalmente entre 1952 y 2007, cada 5 años).             |
| `lifeExp`  | Esperanza de vida al nacer (años).                                           |
| `pop`      | Población total del país ese año.                                            |
| `gdpPercap`| PIB per cápita (Producto Interno Bruto dividido por la población).          |

In [19]:
gapminder = px.data.gapminder()
gapminder2007 = gapminder.query("year==2007")
px.scatter(gapminder2007, x="gdpPercap", y="lifeExp")

🔍 **¿Qué patrones se suelen observar?**

* Relación positiva clara:
    En general, a mayor PIB per cápita, mayor esperanza de vida (aunque no es lineal).

* Disminución de rendimientos crecientes:
    Al principio, pequeños aumentos en el PIB generan grandes aumentos en esperanza de vida, pero luego la mejora se estabiliza.

* Países pobres:
    Se concentran en la parte inferior izquierda (bajo PIB y baja esperanza de vida).

* Países ricos:
    En la parte superior derecha (alto PIB y alta esperanza de vida).

Este gráfico nos muestra que la riqueza económica de un país está relacionada con cuán longeva es su población. Aunque el dinero no compra todo, los países más desarrollados suelen tener mejores condiciones de salud, lo que se refleja en una mayor esperanza de vida.

In [20]:
px.scatter(gapminder2007, x="gdpPercap", y="lifeExp", color="continent")

In [21]:
px.scatter(gapminder2007, x="gdpPercap", y="lifeExp", size="pop", color="continent", size_max=60)

### Matriz

Volvemos al dataframe de las propinas...

In [22]:
px.scatter_matrix(tips, dimensions=['total_bill','tip','size'])

In [23]:
px.scatter_matrix(tips, dimensions=['total_bill','tip','size'], color='sex')

# Referencias

* https://medium.com/plotly/introducing-plotly-express-808df010143d
* https://plotly.com/python/plotly-express/